### ISSUE TITLE
a special version for newbie ; trouble with git and external/legion/Cargo.toml

### ISSUE THREAD

**Issue by laticoda** [smokku/rust_roguelike_tutorial#2]
Hi smokku, thanks for sharing, i am very interested with legion ;

could you please just provide somewhere, a special version for newbies like me, very easy to run without fighting with git and things like external/legion/Cargo.toml
It's ok if it lacks goodies, i just want to study it.
i dont need wasm for testing your work.

--
error: failed to get `legion` as a dependency of package `rust_roguelike_tutorial v0.1.0
Caused by:
  failed to load source for dependency `legion`
  failed to read `/home/xxx/rust_roguelike_tutorial/external/legion/Cargo.toml`

**Comment by smokku** [comment]
I believe that you ar missing:
```sh
git submodule init
git submodule update
```

Anyway, you will find the `Section 3` release under Code / Releases tab.
Download `rust_roguelike_tutorial.zip`, unzip and `cargo run`.
